begin; 

CREATE TABLE anexo( 
      id  integer generated by default as identity primary key     NOT NULL , 
      atividade_id integer    NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      tamanho blob sub_type 1    NOT NULL , 
      local blob sub_type 1    NOT NULL , 
      tipo blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)); 

 CREATE TABLE atividade( 
      id  integer generated by default as identity primary key     NOT NULL , 
      evento_id integer    NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      nome_en blob sub_type 1   , 
      descricao blob sub_type 1   , 
      descricao_en blob sub_type 1   , 
      local_nome blob sub_type 1    NOT NULL , 
      local_geolocalizacao blob sub_type 1   , 
      dt_inicio timestamp    NOT NULL , 
      dt_fim timestamp   , 
 PRIMARY KEY (id)); 

 CREATE TABLE avaliacao_atividade( 
      id  integer generated by default as identity primary key     NOT NULL , 
      inscricao_atividade_id integer    NOT NULL , 
      estrelas float    NOT NULL , 
      comentario blob sub_type 1   , 
      dt_registro timestamp    NOT NULL , 
 PRIMARY KEY (id)); 

 CREATE TABLE avaliacao_evento( 
      id  integer generated by default as identity primary key     NOT NULL , 
      inscricao_id integer    NOT NULL , 
      estrelas float    NOT NULL , 
      comentario blob sub_type 1   , 
      dt_registro timestamp    NOT NULL , 
 PRIMARY KEY (id)); 

 CREATE TABLE evento( 
      id  integer generated by default as identity primary key     NOT NULL , 
      responsavel_id integer    NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      nome_en blob sub_type 1   , 
      descricao blob sub_type 1    NOT NULL , 
      desricao_en blob sub_type 1   , 
      banner blob sub_type 1   , 
      logo blob sub_type 1   , 
      cor blob sub_type 1   , 
      dt_inicio timestamp    NOT NULL , 
      dt_fim timestamp   , 
      contato_nome blob sub_type 1    NOT NULL , 
      contato_email blob sub_type 1    NOT NULL , 
      contato_telefone blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)); 

 CREATE TABLE inscricao( 
      id  integer generated by default as identity primary key     NOT NULL , 
      pessoa_id integer    NOT NULL , 
      evento_id integer    NOT NULL , 
      codigo blob sub_type 1    NOT NULL , 
      dt_ativacao timestamp    NOT NULL , 
      dt_cancelamento timestamp   , 
 PRIMARY KEY (id)); 

 CREATE TABLE inscricao_atividade( 
      id  integer generated by default as identity primary key     NOT NULL , 
      atividade_id integer    NOT NULL , 
      inscricao_id integer    NOT NULL , 
 PRIMARY KEY (id)); 

 CREATE TABLE mensagem( 
      id  integer generated by default as identity primary key     NOT NULL , 
      inscricao_atividade_id integer    NOT NULL , 
      dt_registro timestamp    NOT NULL , 
      conteudo blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)); 

 CREATE TABLE notificacao_atividade( 
      id  integer generated by default as identity primary key     NOT NULL , 
      atividade_id integer    NOT NULL , 
      titulo blob sub_type 1    NOT NULL , 
      titulo_en blob sub_type 1   , 
      conteudo blob sub_type 1    NOT NULL , 
      conteudo_en blob sub_type 1   , 
      logo blob sub_type 1   , 
      dt_notificacao timestamp    NOT NULL , 
 PRIMARY KEY (id)); 

 CREATE TABLE notificacao_evento( 
      id  integer generated by default as identity primary key     NOT NULL , 
      evento_id integer    NOT NULL , 
      titulo blob sub_type 1    NOT NULL , 
      titulo_en blob sub_type 1   , 
      conteudo blob sub_type 1    NOT NULL , 
      conteudo_en blob sub_type 1   , 
      logo blob sub_type 1   , 
      dt_notificacao timestamp    NOT NULL , 
 PRIMARY KEY (id)); 

 CREATE TABLE opcao( 
      id  integer generated by default as identity primary key     NOT NULL , 
      descricao blob sub_type 1    NOT NULL , 
      descricao_en blob sub_type 1   , 
      valor blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)); 

 CREATE TABLE pergunta( 
      id  integer generated by default as identity primary key     NOT NULL , 
      atividade_id integer    NOT NULL , 
      descricao blob sub_type 1    NOT NULL , 
      descricao_en blob sub_type 1   , 
 PRIMARY KEY (id)); 

 CREATE TABLE pergunta_opcao( 
      id  integer generated by default as identity primary key     NOT NULL , 
      pergunta_id integer    NOT NULL , 
      opcao_id integer    NOT NULL , 
 PRIMARY KEY (id)); 

 CREATE TABLE pessoa( 
      id  integer generated by default as identity primary key     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      email blob sub_type 1    NOT NULL , 
      email2 blob sub_type 1   , 
      email3 blob sub_type 1   , 
      foto blob sub_type 1   , 
      token blob sub_type 1   , 
      idioma blob sub_type 1   , 
 PRIMARY KEY (id)); 

 CREATE TABLE responsaveis_atividade( 
      id  integer generated by default as identity primary key     NOT NULL , 
      atividade_id integer    NOT NULL , 
      usuario_id integer    NOT NULL , 
 PRIMARY KEY (id)); 

 CREATE TABLE resposta_pergunta( 
      id  integer generated by default as identity primary key     NOT NULL , 
      atividade_inscricao_id integer    NOT NULL , 
      opcao_id integer    NOT NULL , 
      pergunta_id integer    NOT NULL , 
      dt_registro timestamp    NOT NULL , 
 PRIMARY KEY (id)); 

  
 ALTER TABLE anexo ADD CONSTRAINT fk_anexo_1 FOREIGN KEY (atividade_id) references atividade(id); 
ALTER TABLE atividade ADD CONSTRAINT fk_atividade_1 FOREIGN KEY (evento_id) references evento(id); 
ALTER TABLE avaliacao_atividade ADD CONSTRAINT fk_avaliacao_atividade_1 FOREIGN KEY (inscricao_atividade_id) references inscricao_atividade(id); 
ALTER TABLE avaliacao_evento ADD CONSTRAINT fk_avaliacao_evento_1 FOREIGN KEY (inscricao_id) references inscricao(id); 
ALTER TABLE evento ADD CONSTRAINT fk_evento_1 FOREIGN KEY (responsavel_id) references pessoa(id); 
ALTER TABLE inscricao ADD CONSTRAINT fk_inscricao_2 FOREIGN KEY (evento_id) references evento(id); 
ALTER TABLE inscricao ADD CONSTRAINT fk_inscricao_1 FOREIGN KEY (pessoa_id) references pessoa(id); 
ALTER TABLE inscricao_atividade ADD CONSTRAINT fk_inscricao_atividade_2 FOREIGN KEY (inscricao_id) references inscricao(id); 
ALTER TABLE inscricao_atividade ADD CONSTRAINT fk_inscricao_atividade_1 FOREIGN KEY (atividade_id) references atividade(id); 
ALTER TABLE mensagem ADD CONSTRAINT fk_mensagem_1 FOREIGN KEY (inscricao_atividade_id) references inscricao_atividade(id); 
ALTER TABLE notificacao_atividade ADD CONSTRAINT fk_notificacao_atividade_1 FOREIGN KEY (atividade_id) references atividade(id); 
ALTER TABLE notificacao_evento ADD CONSTRAINT fk_notificacao_evento_1 FOREIGN KEY (evento_id) references evento(id); 
ALTER TABLE pergunta ADD CONSTRAINT fk_pergunta_1 FOREIGN KEY (atividade_id) references atividade(id); 
ALTER TABLE pergunta_opcao ADD CONSTRAINT fk_pergunta_opcao_2 FOREIGN KEY (opcao_id) references opcao(id); 
ALTER TABLE pergunta_opcao ADD CONSTRAINT fk_pergunta_opcao_1 FOREIGN KEY (pergunta_id) references pergunta(id); 
ALTER TABLE responsaveis_atividade ADD CONSTRAINT fk_responsaveis_atividade_1 FOREIGN KEY (atividade_id) references atividade(id); 
ALTER TABLE resposta_pergunta ADD CONSTRAINT fk_resposta_pergunta_3 FOREIGN KEY (pergunta_id) references pergunta(id); 
ALTER TABLE resposta_pergunta ADD CONSTRAINT fk_resposta_pergunta_2 FOREIGN KEY (opcao_id) references opcao(id); 
ALTER TABLE resposta_pergunta ADD CONSTRAINT fk_resposta_pergunta_1 FOREIGN KEY (atividade_inscricao_id) references inscricao_atividade(id); 
 
 commit;